- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: ping
  host: odin.dhcp.home
  name: Odin
- platform: ping
  host: blackpanther.dhcp.home
  name: Blackpanther
