- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: ping
  host: odin.gavinmogan.com
  name: Odin
- platform: ping
  host: blackpanther.gavinmogan.com
  name: Blackpanther