homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.227703
  longitude: -123.0111478
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 108
  # metric for Metric, imperial for Imperial
  whitelist_external_dirs:
    - /config
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Vancouver
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret http_trusted_proxy
  customize:
    light.bar_light:
      friendly_name: Bar Lights
      icon: mdi:led-strip
    light.kitchen_cabinets:
      friendly_name: Kitchen Cabinets Lights
      icon: mdi:led-strip
    light.media_center_lights:
      friendly_name: Media Center Lights
      icon: mdi:led-strip
    switch.behind_tv_lamp_switch:
      friendly_name: Behind TV Lamp
      icon: mdi:lamp
    switch.bookshelf_switch:
      friendly_name: Bookshelf Lamp
      icon: mdi:lamp
    switch.kitchen_lamp_switch:
      friendly_name: Kitchen Lamp
      icon: mdi:lamp
    switch.computer_lamp_switch:
      friendly_name: Computer Desk Lamp
      icon: mdi:lamp
    script.movie_mode:
      friendly_name: Movie Mode
    script.goodnight:
      friendly_name: Goodnight
    scene.l1:
      friendly_name: Lights On
    scene.lights_off:
      friendly_name: Lights off
    group.people:
      hidden: false
    group.all_lights:
      hidden: false
    group.all_scripts:
      hidden: false
    group.all_switches:
      hidden: false

lovelace:
  mode: yaml

auth:

# custom_updater:
system_health:

recorder:
  #  db_url: !secret recorder_db_url
  purge_keep_days: 30

# Enables the frontend
frontend:

# Enables configuration UI
config:

# hassio:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  cors_allowed_origins:
    - !secret http_base_domain
    - https://cast.home-assistant.io
  trusted_proxies:
    - !secret http_trusted_proxy
  ip_ban_enabled: true

google_assistant:
  project_id: !secret google_actions_project_id
  exposed_domains:
    - scene
    - script

updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  include:
    entities:
      - switch.living_room_switch_switch
    domains:
      - light
      - switch

# Track the sun
sun:

# enable mqtt
mqtt:
  broker: !secret mqtt_broker
  discovery: true

zwave:
  usb_path: /dev/ttyACM0

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
  - platform: darksky
    api_key: !secret darksky_api_key

owntracks:

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

binary_sensor: !include binary_sensors.yaml
media_player: !include media_players.yaml
zone: !include zones.yaml
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
switch: !include switches.yaml
cover: !include covers.yaml
light: !include lights.yaml
camera: !include cameras.yaml
shell_command: !include shell_commands.yaml

history_graph:
  temperature:
    entities:
      - sensor.yr_temperature
      - sensor.front_door_motion_temperature

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: CA
  devices:
    - device_id: !secret dyson_device_1_name
      device_ip: !secret dyson_device_1_ip

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave
# unifi:
#   controllers:
#     - host: !secret device_tracker_unifi_host
#       # username: !secret device_tracker_unifi_username
#       # password: !secret device_tracker_unifi_password
#       site: !secret device_tracker_unifi_site_name

cast:
  media_player:
    #- host: 172.16.10.175
