- platform: yr
  monitored_conditions:
    - temperature
    - precipitation
# - platform: transmission
#   host: !secret transmission_host
#   port: !secret transmission_port
#   username: !secret transmission_user
#   password: !secret transmission_pass
#   monitored_variables:
#     - 'current_status'
#     - 'download_speed'
#     - 'upload_speed'
# # Reformat the speed sensors to be in Kbp/s
# - platform: template
#   sensors:
#     transmission_down_speed_kbps:
#       value_template: '{{ states.sensor.transmission_down_speed.state | multiply(1024) }}'
#       friendly_name: 'Transmission Down Speed'
#       unit_of_measurement: 'kB/s'
#     transmission_up_speed_kbps:
#       value_template: '{{ states.sensor.transmission_up_speed.state | multiply(1024) }}'
#       friendly_name: 'Transmission Up Speed'
#       unit_of_measurement: 'kB/s'
#- platform: moon

- platform: time_date
  display_options:
    - "time"
    - "date"

- platform: darksky
  api_key: !secret darksky_api_key
  update_interval:
    minutes: 30
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - nearest_storm_distance

#
# Friendly Date
# Thursday June 10th, 2017
#
- platform: template
  sensors:
    friendly_date:
      friendly_name: "Today's Date"
      value_template: "{{ now().strftime('%A %B %e, %Y') }}"

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db
    - /config/home-assistant.log

- platform: speedtest
  server_id: 14487
  hour:
    - 0
    - 3
    - 6
    - 9
    - 12
    - 15
    - 18
    - 21
  monitored_conditions:
    - ping
    - download
    - upload

- platform: uptime
  name: HA Uptime
  unit_of_measurement: hours

- platform: rest
  name: SpaceX
  json_attributes:
    - mission_name
    - launch_site
    - rocket
  value_template: '{{ value_json["launch_date_unix"] }}'
  resource: "https://api.spacexdata.com/v2/launches/next"

- platform: template
  sensors:
    spacex_next_launch_date:
      friendly_name: "Next Launch Date"
      value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%m/%d/%Y %H:%M")}}'
    spacex_next_rocket:
      friendly_name: "Rocket"
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
    spacex_next_landing_type:
      friendly_name: "Landing Type"
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["first_stage"]["cores"][0]["landing_type"] }}'
    spacex_next_launch_site:
      friendly_name: "Launch Site"
      value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name"] }}'
    spacex_next_mission_name:
      friendly_name: "Mission Name"
      value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'
