- platform: yr
  monitored_conditions:
    - temperature
    - precipitation

- platform: time_date
  display_options:
    - "time"
    - "date"

- platform: darksky
  api_key: !secret darksky_api_key
  scan_interval: '00:30:00'
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - nearest_storm_distance

#
# Friendly Date
# Thursday June 10th, 2017
#
- platform: template
  sensors:
    friendly_date:
      friendly_name: "Today's Date"
      value_template: "{{ now().strftime('%A %B %e, %Y') }}"

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db
    - /config/home-assistant.log

- platform: uptime
  name: HA Uptime
  unit_of_measurement: hours

#- platform: sonarr_upcoming_media
#  api_key: !secret sonarr_api_key
#  host: !secret sonarr_hostname
#  port: 443
#  days: 7
#  ssl: true
#
#- platform: radarr_upcoming_media
#  api_key: !secret radarr_api_key
#  host: !secret radarr_hostname
#  port: 443
#  days: 60
#  ssl: true
#  theaters: false
#
#- platform: trakt
#  id: !secret trakt_client_id
#  secret: !secret trakt_client_secret
#  username: halkeye
#  days: 10
#  exclude:
#    - 'The Bachelor'
