- platform: yr
  monitored_conditions:
    - temperature
    - precipitation

- platform: time_date
  display_options:
    - "time"
    - "date"

- platform: darksky
  api_key: !secret darksky_api_key
  scan_interval: '00:30:00'
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - nearest_storm_distance

#
# Friendly Date
# Thursday June 10th, 2017
#
- platform: template
  sensors:
    friendly_date:
      friendly_name: "Today's Date"
      value_template: "{{ now().strftime('%A %B %e, %Y') }}"

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db
    - /config/home-assistant.log

- platform: uptime
  name: HA Uptime
  unit_of_measurement: hours

- platform: rest
  name: SpaceX
  json_attributes:
    - mission_name
    - launch_site
    - rocket
  value_template: '{{ value_json["launch_date_unix"] }}'
  resource: "https://api.spacexdata.com/v2/launches/next"

- platform: template
  sensors:
    spacex_next_launch_date:
      friendly_name: "Next Launch Date"
      value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%m/%d/%Y %H:%M")}}'
    spacex_next_rocket:
      friendly_name: "Rocket"
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
    spacex_next_landing_type:
      friendly_name: "Landing Type"
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["first_stage"]["cores"][0]["landing_type"] }}'
    spacex_next_launch_site:
      friendly_name: "Launch Site"
      value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name"] }}'
    spacex_next_mission_name:
      friendly_name: "Mission Name"
      value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'

#- platform: sonarr_upcoming_media
#  api_key: !secret sonarr_api_key
#  host: !secret sonarr_hostname
#  port: 443
#  days: 7
#  ssl: true
#
#- platform: radarr_upcoming_media
#  api_key: !secret radarr_api_key
#  host: !secret radarr_hostname
#  port: 443
#  days: 60
#  ssl: true
#  theaters: false
#
#- platform: trakt
#  id: !secret trakt_client_id
#  secret: !secret trakt_client_secret
#  username: halkeye
#  days: 10
#  exclude:
#    - 'The Bachelor'
