- platform: mqtt
  name: "Master Bedroom Blinds"
  command_topic: "home/blinds/set"
  payload_off: "4|off"
  payload_on: "4|on"
- platform: mqtt
  name: "Second Bedroom Blinds"
  command_topic: "home/blinds/set"
  ### both secondary bedroom and far blinds are set to 1 right now
  payload_on: "1|on"
  payload_off: "1|off"
- platform: mqtt
  name: "Desk Blinds"
  command_topic: "home/blinds/set"
  payload_on: "3|on"
  payload_off: "3|off"
- platform: mqtt
  name: "Living Room Blinds"
  command_topic: "home/blinds/set"
  payload_on: "2|on"
  payload_off: "2|off"
- platform: mqtt
  name: "Far Living Room Blinds"
  command_topic: "home/blinds/set"
  payload_on: "1|on"
  payload_off: "1|off"
- platform: mqtt
  name: "Shield"
  state_topic: "media/cec/8"
  state_on: "on"
  state_off: "off"
  command_topic: "media/cec/8/cmd"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "Stereo"
  state_topic: "media/cec/5"
  state_on: "on"
  state_off: "off"
  command_topic: "media/cec/5/cmd"
  payload_on: "on"
  payload_off: "off"
  retain: true
- platform: mqtt
  name: "TV"
  state_topic: "media/cec/0"
  state_on: "on"
  state_off: "off"
  command_topic: "media/cec/0/cmd"
  payload_on: "on"
  payload_off: "off"
  retain: true
