- platform: mqtt
  name: "Master Bedroom Blinds"
  command_topic: "home/blinds/set"
  payload_on: "8|on"
  payload_off: "8|off"
- platform: mqtt
  name: "Second Bedroom Blinds"
  command_topic: "home/blinds/set"
  payload_on: "4|on"
  payload_off: "4|off"
- platform: mqtt
  name: "Desk Blinds"
  command_topic: "home/blinds/set"
  payload_on: "3|on"
  payload_off: "3|off"
- platform: mqtt
  name: "Living Room Blinds"
  command_topic: "home/blinds/set"
  payload_on: "2|on"
  payload_off: "2|off"
- platform: mqtt
  name: "Far Living Room Blinds"
  command_topic: "home/blinds/set"
  payload_on: "1|on"
  payload_off: "1|off"